/*#include<iostream>
using namespace std;
int main()
{
    int a=4;
    float b=3.14;
    char name='c';
    cout<<"Hello This is Coder ";
    cout<<" The value of a is : "<<a;
    cout<<" The value of b is : "<<b;
    cout<<" The name is : "<<name;
    return 0;
}*/


/*#include<iostream>
using namespace std;
int main()
{
    int a=4;
    float b=3.14;
    char name='c';
    cout<<"Hello This is Coder ";
    cout<<"\n The value of a is : "<<a;
    cout<<"\n The value of b is : "<<b;
    cout<<"\n The name is : "<<name;
    return 0;
}*/


#include<iostream>
using namespace std;
int main()
{
    int a=4;
    float b=3.14;
    char name='c';
    cout<<"Hello This is Coder "<<endl;
    cout<<" The value of a is : "<<a<<endl;
    cout<<" The value of b is : "<<b<<endl;
    cout<<" The name is : "<<name<<endl;
    return 0;
}