#include<iostream>
using namespace std;
int main()
{
    string name ;
    cout<<"Enter the name of the person : ";
    cin>>name;
    if(name=="Krishan")
    {
        cout<<"Owner of the House";
    }
    if(name=="Jyoti")
    {
        cout<<"Wife of the House Owner";
    }
    if(name=="Reshu")
    {
        cout<<"Daughter of the House Owner";
    }
    if(name=="Anushka")
    {
        cout<<"Daughter of the House Owner";
    }
    if(name=="Yuvraj")
    {
        cout<<"Son of the House Owner";
    }
    return 0;
}